"use client";
import "./globals.css";
import {
  QueryClientProvider,
} from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { useState } from "react";
import { Toaster } from "@/components/ui/sonner";
import { getQueryClient } from "@/lib/queryClient";
import { SupabaseProvider } from "@/components/SupabaseProvider";
import { AuthProvider } from "@/lib/context/authContext";
import { GamificationProvider } from "@/components/gamification/GamificationProvider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => getQueryClient());

  return (
    <SupabaseProvider>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <GamificationProvider>
            <html lang="en">
              <body className="antialiased">
                {children}
                <Toaster />
              </body>
            </html>
          </GamificationProvider>
        </AuthProvider>
        {process.env.NODE_ENV === "development" && (
          <ReactQueryDevtools initialIsOpen={false} />
        )}
      </QueryClientProvider>
    </SupabaseProvider>
  );
}
