export const categoryColors: Record<string, string> = {
  meats: "bg-rose-600 text-white",
  seafood: "bg-cyan-600 text-white",
  dairy: "bg-blue-600 text-white",
  dairy_and_cheese: "bg-blue-600 text-white",
  grains: "bg-amber-600 text-white",
  grains_and_cereals: "bg-amber-600 text-white",
  legumes: "bg-lime-700 text-white",
  flours_and_sugars: "bg-orange-600 text-white",
  spices: "bg-fuchsia-600 text-white",
  herbs: "bg-green-600 text-white",
  herbs_and_spices: "bg-green-600 text-white",
  condiments_and_sauces: "bg-red-600 text-white",
  vegetables: "bg-emerald-600 text-white",
  fruits: "bg-pink-600 text-white",
  nuts_and_seeds: "bg-yellow-700 text-white",
  bakery_and_pastry: "bg-stone-600 text-white",
  eggs_and_derivatives: "bg-sky-600 text-white",
  eggs: "bg-sky-600 text-white",
  oils_and_fats: "bg-yellow-600 text-white",
  beverages_non_alcoholic: "bg-teal-600 text-white",
  beverages_alcoholic: "bg-purple-700 text-white",
  supplements_and_vitamins: "bg-violet-600 text-white",
  desserts_and_sweets: "bg-rose-500 text-white",
  frozen_foods: "bg-indigo-600 text-white",
  canned_goods: "bg-slate-600 text-white",
  ready_to_eat: "bg-zinc-700 text-white",

  // Legacy / translated aliases
  Dairy: "bg-blue-600 text-white",
  Meat: "bg-rose-600 text-white",
  Produce: "bg-emerald-600 text-white",
  Grains: "bg-amber-600 text-white",
  Lácteos: "bg-blue-600 text-white",
  Lacteos: "bg-blue-600 text-white",
  Carnes: "bg-rose-600 text-white",
  Frutas: "bg-pink-600 text-white",
  Verduras: "bg-emerald-600 text-white",
};

export const categoryNamesEs: Record<string, string> = {
  meats: "Carnes",
  seafood: "Mariscos y pescados",
  dairy: "Lácteos",
  dairy_and_cheese: "Lácteos y quesos",
  grains: "Granos",
  grains_and_cereals: "Granos y cereales",
  legumes: "Legumbres",
  flours_and_sugars: "Harinas y azúcares",
  spices: "Especias",
  herbs: "Hierbas",
  herbs_and_spices: "Hierbas y especias",
  condiments_and_sauces: "Condimentos y salsas",
  vegetables: "Verduras",
  fruits: "Frutas",
  nuts_and_seeds: "Frutos secos y semillas",
  bakery_and_pastry: "Panadería y repostería",
  eggs_and_derivatives: "Huevos y derivados",
  eggs: "Huevos",
  oils_and_fats: "Aceites y grasas",
  beverages_non_alcoholic: "Bebidas sin alcohol",
  beverages_alcoholic: "Bebidas alcohólicas",
  supplements_and_vitamins: "Suplementos y vitaminas",
  desserts_and_sweets: "Postres y dulces",
  frozen_foods: "Congelados",
  canned_goods: "Enlatados",
  ready_to_eat: "Listos para comer",

  Dairy: "Lácteos",
  Meat: "Carnes",
  Produce: "Productos frescos",
  Grains: "Granos",
  Lácteos: "Lácteos",
  Lacteos: "Lácteos",
  Carnes: "Carnes",
  Frutas: "Frutas",
  Verduras: "Verduras",
};
