export const categoryColors: Record<string, string> = {
  meats: "bg-rose-600 text-white",
  seafood: "bg-cyan-600 text-white",
  dairy: "bg-blue-600 text-white",
  dairy_and_cheese: "bg-blue-600 text-white",
  grains: "bg-amber-600 text-white",
  grains_and_cereals: "bg-amber-600 text-white",
  legumes: "bg-lime-700 text-white",
  flours_and_sugars: "bg-orange-600 text-white",
  spices: "bg-fuchsia-600 text-white",
  herbs: "bg-green-600 text-white",
  herbs_and_spices: "bg-green-600 text-white",
  condiments_and_sauces: "bg-red-600 text-white",
  vegetables: "bg-emerald-600 text-white",
  fruits: "bg-pink-600 text-white",
  nuts_and_seeds: "bg-yellow-700 text-white",
  bakery_and_pastry: "bg-stone-600 text-white",
  eggs_and_derivatives: "bg-sky-600 text-white",
  eggs: "bg-sky-600 text-white",
  oils_and_fats: "bg-yellow-600 text-white",
  beverages_non_alcoholic: "bg-teal-600 text-white",
  beverages_alcoholic: "bg-purple-700 text-white",
  supplements_and_vitamins: "bg-violet-600 text-white",
  desserts_and_sweets: "bg-rose-500 text-white",
  frozen_foods: "bg-indigo-600 text-white",
  canned_goods: "bg-slate-600 text-white",
  ready_to_eat: "bg-zinc-700 text-white",

  // Legacy / translated aliases
  Dairy: "bg-blue-600 text-white",
  Meat: "bg-rose-600 text-white",
  Produce: "bg-emerald-600 text-white",
  Grains: "bg-amber-600 text-white",
  Lácteos: "bg-blue-600 text-white",
  Lacteos: "bg-blue-600 text-white",
  Carnes: "bg-rose-600 text-white",
  Frutas: "bg-pink-600 text-white",
  Verduras: "bg-emerald-600 text-white",
};